packages:
  - backend
  - frontend

overrides:
  axios: '>=1.20.0'
  brace-expansion@5: 5.0.12
  fast-uri@3: 3.1.6
  sonos@1.14.3>ip: '-'

allowBuilds:
  argon2: true
  better-sqlite3: true
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true

patchedDependencies:
  sonos@1.14.3: patches/sonos@1.14.3.patch
